version: "3.8"

services:
  nota_backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  nota_postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./post_data:/var/lib/postgresql/data

volumes:
  postgres_data:
